### ISSUE TITLE
Your Initials

### ISSUE THREAD

**Issue by NightHawk2007** [D-Stan6667/Learning-Rust#1]
Your Initials are R B ?

Do not reply overtly. Just acknowledge.

You ask about me to our mutual friend axototle.

Can you help me with some projects?

**Comment by D-Stan6667** [comment]
> Your Initials are R B ?
> 
> Do not reply overtly. Just acknowledge.
> 
> You ask about me to our mutual friend axototle.
> 
> Can you help me with some projects?

I am not RB. You have the wrong person.

**Comment by NightHawk2007** [comment]
Who are you? Your initials?
